name: AmazingTitles
api-version: 1.13
version: 5.0
main: com.zitemaker.amazingtitles.code.internal.Booter
author: M3II0
softdepend:
  - CMI
commands:
  amazingtitles:
    permission: "amazingtitles.command"
    aliases:
      - at